name: BTC News Crawler

on:
  schedule:
    # RSS抓取任务 (UTC时间，比北京时间晚8小时)
    - cron: '0 16,4,22,11 * * *'  # 对应北京时间 0:00,12:00,6:00,19:00
    
    # 摘要生成任务
    - cron: '0 13 * * *'  # 对应北京时间 21:00
  
  workflow_dispatch:  # 允许手动触发

jobs:
  rss-crawler:
    if: github.event.schedule != '0 13 * * *'  # 不是21:00的定时任务才执行
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
      - name: Run RSS crawler
        env:
          VOLCENGINE_API_KEY: ${{ secrets.VOLCENGINE_API_KEY }}
        run: python main.py --mode rss

  news-summary:
    if: github.event.schedule == '0 13 * * *'  # 只在21:00的定时任务执行
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate and push summary
        env:
          VOLCENGINE_API_KEY: ${{ secrets.VOLCENGINE_API_KEY }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: python main.py --mode summary_push