name: BTC News Crawler

on:
  schedule:
    # RSS抓取任务 (UTC时间，比北京时间晚8小时)
    - cron: '0 6,22,14 * * *'  # 对应北京时间 14:00,6:00,22:00
    
    # 摘要生成任务
    - cron: '0 0 * * 1,3,5'  # 对应北京时间 8:00，每周一、三、五、六执行
    
    # 新增：周六summary_write任务
    - cron: '0 0 * * 6'  # 对应北京时间 10:00，每周六执行summary_write
  
  workflow_dispatch:  # 允许手动触发

jobs:
  rss-crawler:
    # 不是XX:XX的定时任务才执行
    if: github.event.schedule != '0 0 * * 1,3,5' && github.event.schedule != '0 0 * * 6'
    runs-on: windows-latest  # 修改为Windows环境
    
    # 新增：为任务授予写入权限
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
      - name: Run RSS crawler
        env:
          VOLCENGINE_API_KEY: ${{ secrets.VOLCENGINE_API_KEY }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          PYTHONUTF8: "1"
        run: python main.py --mode rss
      
      # 使用 git 命令提交并推送文件
      - name: Commit and push if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ssr_list.db
          git commit -m "Update ssr_list.db" || exit 0
          git push
  
  news-summary:
    # 不再依赖rss-crawler任务，独立执行
    # needs: rss-crawler
    # 只在20:00的定时任务执行
    if: github.event.schedule == '0 0 * * 1,3,5'
    runs-on: ubuntu-latest

    # 新增：为任务授予写入权限
    permissions:
      contents: write

    steps:
      # 在此任务开始时，checkout 会自动获取 rss-crawler 任务提交的最新文件
      - uses: actions/checkout@v2
      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate and push summary
        env:
          VOLCENGINE_API_KEY: ${{ secrets.VOLCENGINE_API_KEY }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }} 
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          ALI_API_KEY: ${{ secrets.ALI_API_KEY }}
          PYTHONUTF8: "1"
        run: python main.py --mode summary_push

      # 使用 git 命令提交并推送文件
      - name: Commit and push if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add latest_prompt.txt latest_summary.md
          git commit -m "Update latest_prompt.txt and latest_summary.md" || exit 0
          git push

  # 新增：周六summary_write任务
  summary-write:
    # 只在周六10:00的定时任务执行
    if: github.event.schedule == '0 0 * * 6'
    runs-on: ubuntu-latest

    # 新增：为任务授予写入权限
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate summary and write to document
        env:
          VOLCENGINE_API_KEY: ${{ secrets.VOLCENGINE_API_KEY }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          ALI_API_KEY: ${{ secrets.ALI_API_KEY }}
          PYTHONUTF8: "1"
        run: python main.py --mode summary_write

      # 使用 git 命令提交并推送文件
      - name: Commit and push if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add latest_summary.md latest_summary_chunks.md
          git commit -m "Update summary files from summary_write mode" || exit 0
          git push
