name: BTC News Crawler

on:
  schedule:
    # RSS抓取任务 (UTC时间，比北京时间晚8小时)
    - cron: '0 6,22,14 * * *'  # 对应北京时间 14:00,6:00,22:00
  
  workflow_dispatch:  # 允许手动触发

jobs:
  rss-crawler:
    # 不是XX:XX的定时任务才执行
    if: github.event.schedule != '10 23 * * 0,1,2,3,4' && github.event.schedule != '0 0 * * 0'
    runs-on: windows-latest  # 修改为Windows环境
    
    # 新增：为任务授予写入权限
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
      - name: Run RSS crawler
        env:
          VOLCENGINE_API_KEY: ${{ secrets.VOLCENGINE_API_KEY }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          PYTHONUTF8: "1"
        run: python main.py --mode rss
      
      # 使用 git 命令提交并推送文件
      # - name: Commit and push if changed
      #   run: |
      #     git config --global user.email "actions@github.com"
      #     git config --global user.name "GitHub Actions"
      #     git add ssr_list.db
      #     git commit -m "Update ssr_list.db" || exit 0
      #     git push