name: BTC News Crawler

on:
  schedule:
    # RSS抓取任务 (UTC时间，比北京时间晚8小时)
    - cron: '0 10,2,18 * * *'  # 对应北京时间 18:00,10:00,2:00
    
    # 摘要生成任务
    - cron: '0 12 * * *'  # 对应北京时间 20:00
  
  workflow_dispatch:  # 允许手动触发

jobs:
  rss-crawler:
    # 不是20:00的定时任务才执行
    if: github.event.schedule != '0 12 * * *'
    runs-on: windows-latest  # 修改为Windows环境
    
    # 新增：为任务授予写入权限
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
      - name: Run RSS crawler
        env:
          VOLCENGINE_API_KEY: ${{ secrets.VOLCENGINE_API_KEY }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          PYTHONUTF8: "1"
        run: python main.py --mode rss
      
      # 使用 git 命令提交并推送文件
      - name: Commit and push if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ssr_list.db latest_prompt.txt latest_summary.md
          git commit -m "Update workflow data files" || exit 0
          git push
  
  news-summary:
    # 不再依赖rss-crawler任务，独立执行
    # needs: rss-crawler
    # 只在20:00的定时任务执行
    if: github.event.schedule == '0 12 * * *'
    runs-on: ubuntu-latest
    steps:
      # 在此任务开始时，checkout 会自动获取 rss-crawler 任务提交的最新文件
      - uses: actions/checkout@v2
      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate and push summary
        env:
          VOLCENGINE_API_KEY: ${{ secrets.VOLCENGINE_API_KEY }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          FEISHU_WEBHOOK_URL: ${{ secrets.FEISHU_WEBHOOK_URL }}
          PYTHONUTF8: "1"
        run: python main.py --mode summary_push
